[project]
name = "pyplay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.12",
    "anthropic>=0.46.0",
    "requests>=2.32.3",
]
