create table numbers_small_tbl(
    -- note: primary key implies NOT NULL and UNIQUE
    -- primary key also automatically creates an index on the column
    id integer primary key generated by default as identity,
    b integer,
    c integer
);


create table numbers_large_tbl(
    -- note: primary key implies NOT NULL and UNIQUE
    -- primary key also automatically creates an index on the column
    id integer primary key generated by default as identity,
    b integer,
    c integer
);

-- use of SRF in select clause is postgres-specific, not SQL standard
insert into numbers_small_tbl (b, c) 
select generate_series(1,100), generate_series(100,1, -1); 

insert into numbers_large_tbl (b, c)
select num, 100000-num
from generate_series(1, 100000) num;
